export const defaultGames = [
  {
    id: "fire-red",
    title: "Pokemon Fire Red",
    region: "Kanto",
    generation: 1,
    color: "#e53e3e",
    pokedexFile: "pokemon-fire-red",
    totalPokemon: 151,
    versionSlug: "firered",
    steps: [
      "Start a new game and set your player name and rival name",
      "Leave your house in Pallet Town and meet Professor Oak",
      "Go to Oak's Lab and choose your starter Pokemon",
      "Battle your rival in Oak's Lab",
      "Travel north to Viridian City",
      "Pick up Oak's Parcel from the Viridian Poke Mart",
      "Return to Pallet Town and deliver Oak's Parcel",
      "Receive the Pokedex from Professor Oak",
      "Get Poke Balls and begin catching Pokemon",
      "Head back to Viridian City and prepare for Route 2",
      "Travel through Viridian Forest",
      "Reach Pewter City and stock up on supplies",
      "Defeat Brock and earn the Boulder Badge",
      "Travel east on Route 3",
      "Enter Mt. Moon and explore its paths",
      "Defeat Team Rocket in Mt. Moon",
      "Choose one of the fossils and exit Mt. Moon",
      "Arrive in Cerulean City",
      "Defeat your rival north of Cerulean City",
      "Beat the Nugget Bridge trainers",
      "Defeat Team Rocket near Bill's house",
      "Help Bill and receive the S.S. Ticket",
      "Return to Cerulean City Gym and defeat Misty",
      "Travel to Vermilion City",
      "Board the S.S. Anne",
      "Battle your rival on the S.S. Anne",
      "Receive HM01 Cut from the Captain",
      "Teach Cut and access Vermilion Gym",
      "Solve Lt. Surge's trash can puzzle",
      "Defeat Lt. Surge and earn the Thunder Badge",
      "Travel through Diglett's Cave if desired for Flash support",
      "Pass through Route 9 and Route 10",
      "Enter Rock Tunnel and make your way through",
      "Reach Lavender Town",
      "Travel west to Celadon City",
      "Visit the Celadon Department Store and prepare your team",
      "Defeat Erika and earn the Rainbow Badge",
      "Enter the Rocket Game Corner hideout",
      "Clear Team Rocket Hideout",
      "Defeat Giovanni in the hideout and get the Silph Scope",
      "Return to Lavender Town and enter Pokemon Tower",
      "Reveal the ghost with the Silph Scope",
      "Rescue Mr. Fuji and receive the Poke Flute",
      "Use the Poke Flute to wake a sleeping Snorlax",
      "Open the route toward Fuchsia City",
      "Reach Fuchsia City and get the Safari Zone items",
      "Enter the Safari Zone and find the Gold Teeth",
      "Obtain HM03 Surf in the Safari Zone",
      "Give the Gold Teeth to the Warden and receive HM04 Strength",
      "Defeat Koga and earn the Soul Badge",
      "Travel to Saffron City",
      "Enter Silph Co. after obtaining access",
      "Fight through Silph Co. and reach the upper floors",
      "Defeat your rival inside Silph Co.",
      "Defeat Giovanni in Silph Co. and save the company",
      "Receive the Master Ball from the Silph president",
      "Defeat Sabrina and earn the Marsh Badge",
      "Travel by Surf to Cinnabar Island",
      "Explore the Pokemon Mansion for the Secret Key",
      "Unlock Cinnabar Gym",
      "Defeat Blaine and earn the Volcano Badge",
      "Return to Viridian City",
      "Enter Viridian Gym and complete the spinner puzzle",
      "Defeat Giovanni and earn the Earth Badge",
      "Head west from Viridian City to Victory Road",
      "Pass all badge checks and explore Victory Road",
      "Reach the Indigo Plateau",
      "Challenge the Elite Four: Lorelei",
      "Challenge the Elite Four: Bruno",
      "Challenge the Elite Four: Agatha",
      "Challenge the Elite Four: Lance",
      "Defeat your rival and become Champion",
      "Watch the Hall of Fame sequence and complete the main story",
      "Receive the National Dex requirements / postgame access",
      "Visit the Sevii Islands if continuing the postgame",
      "Complete the postgame Team Rocket and Ruby/Sapphire questline",
    ],
  },
  {
    id: "emerald",
    title: "Pokemon Emerald",
    region: "Hoenn",
    generation: 3,
    color: "#38a169",
    pokedexFile: "pokemon-emerald",
    totalPokemon: 386,
    versionSlug: "emerald",
    steps: [
      "Start a new game in Littleroot Town",
      "Set your room clock and meet your neighbor rival",
      "Go north to Route 101 and help Professor Birch",
      "Choose Treecko, Torchic, or Mudkip",
      "Defeat the wild Pokemon attacking Birch",
      "Visit Professor Birch's lab and receive your Pokedex",
      "Travel to Route 103 and battle May/Brendan",
      "Receive Poke Balls and begin catching Pokemon",
      "Travel to Oldale Town and then west to Petalburg City",
      "Meet your dad Norman in Petalburg Gym",
      "Continue to Rustboro City through Petalburg Woods",
      "Defeat Roxanne and earn the Stone Badge",
      "Help recover the Devon Goods from Team Aqua/Magma",
      "Deliver the Devon Goods and receive tasks from Mr. Stone",
      "Travel to Dewford Town by boat",
      "Explore Granite Cave and deliver the letter to Steven",
      "Return to Dewford Gym and defeat Brawly",
      "Sail to Slateport City",
      "Deliver the Devon Goods at the harbor and trigger the Team Aqua/Magma event",
      "Travel north to Mauville City",
      "Defeat Wally if encountered and prepare for the gym",
      "Defeat Wattson and earn the Dynamo Badge",
      "Head north to Route 111 and Route 112",
      "Travel through Fiery Path and reach Fallarbor area",
      "Help recover the Meteorite from Mt. Chimney / Meteor Falls events",
      "Battle Team Aqua/Magma at Mt. Chimney",
      "Descend to Lavaridge Town",
      "Defeat Flannery and earn the Heat Badge",
      "Return to Petalburg City",
      "Defeat Norman and earn the Balance Badge",
      "Receive HM03 Surf from Wally's family",
      "Travel east and use Surf where needed",
      "Reach Fortree City after the Weather Institute events",
      "Defeat Team Aqua/Magma at the Weather Institute",
      "Use the Devon Scope to reveal the invisible Kecleon",
      "Defeat Winona and earn the Feather Badge",
      "Travel toward Lilycove City",
      "Clear the Team Aqua/Magma hideout near Lilycove",
      "Sail to Mossdeep City",
      "Defeat Tate and Liza and earn the Mind Badge",
      "Visit the Space Center event in Mossdeep",
      "Dive to reach Seafloor Cavern",
      "Confront Team Aqua/Magma in Seafloor Cavern",
      "Trigger the Groudon and Kyogre awakening crisis",
      "Travel to Sootopolis City",
      "Wake Rayquaza and stop the weather crisis",
      "Return to Sootopolis Gym",
      "Defeat Wallace and earn the Rain Badge",
      "Travel east through Routes 127-128 and then north",
      "Pass Ever Grande City and Victory Road",
      "Reach the Pokemon League",
      "Challenge Sidney of the Elite Four",
      "Challenge Phoebe of the Elite Four",
      "Challenge Glacia of the Elite Four",
      "Challenge Drake of the Elite Four",
      "Defeat Champion Wallace and become Champion",
      "Complete the main story and unlock postgame Battle Frontier content",
    ],
  },
  {
    id: "platinum",
    title: "Pokemon Platinum",
    region: "Sinnoh",
    generation: 4,
    color: "#718096",
    pokedexFile: "pokemon-platinum",
    totalPokemon: 493,
    versionSlug: "platinum",
    steps: [
      "Start a new game in Twinleaf Town",
      "Go with Barry to Lake Verity",
      "Meet Professor Rowan and choose your starter Pokemon",
      "Battle your rival Barry",
      "Return home and begin your journey properly",
      "Visit Sandgem Town and receive the Pokedex",
      "Learn catching basics and prepare your team",
      "Travel to Jubilife City",
      "Meet key NPCs and continue north",
      "Reach Oreburgh City",
      "Defeat Roark and earn the Coal Badge",
      "Return through Jubilife and head north toward Eterna",
      "Defeat Team Galactic at Valley Windworks",
      "Clear Eterna Forest and arrive at Eterna City",
      "Defeat Gardenia and earn the Forest Badge",
      "Enter Team Galactic's Eterna Building and clear it",
      "Bike south and continue your journey",
      "Travel through Mt. Coronet paths and route connections",
      "Reach Hearthome City",
      "Continue traveling until Fantina is available if needed",
      "Reach Veilstone City",
      "Defeat Maylene and earn the Cobble Badge",
      "Clear the Team Galactic warehouse / story events in Veilstone",
      "Travel south to Pastoria City",
      "Defeat Crasher Wake and earn the Fen Badge",
      "Pursue Team Galactic after the Pastoria events",
      "Visit Celestic Town and continue the story",
      "Return to Hearthome City",
      "Defeat Fantina and earn the Relic Badge",
      "Travel west to Canalave City",
      "Defeat Byron and earn the Mine Badge",
      "Travel to Iron Island if desired for training and items",
      "Handle the Canalave / library / lake story events",
      "Travel north to Snowpoint City",
      "Defeat Candice and earn the Icicle Badge",
      "Storm Team Galactic HQ in Veilstone City",
      "Obtain the key/card and free the captured legendary",
      "Climb Mt. Coronet toward Spear Pillar",
      "Defeat Cyrus at Spear Pillar",
      "Enter the Distortion World",
      "Navigate the Distortion World puzzles",
      "Defeat Cyrus inside the Distortion World",
      "Defeat or capture Giratina",
      "Return to the normal world and resume the badge quest",
      "Travel to Sunyshore City",
      "Defeat Volkner and earn the Beacon Badge",
      "Head to Victory Road via the Pokemon League route",
      "Explore Victory Road and reach the League",
      "Challenge Aaron of the Elite Four",
      "Challenge Bertha of the Elite Four",
      "Challenge Flint of the Elite Four",
      "Challenge Lucian of the Elite Four",
      "Defeat Champion Cynthia and become Champion",
      "Complete the main story and unlock the postgame areas",
    ],
  },
  {
    id: "heart-gold",
    title: "Pokemon HeartGold",
    region: "Johto",
    generation: 2,
    color: "#d69e2e",
    pokedexFile: "pokemon-heart-gold",
    totalPokemon: 493,
    versionSlug: "heartgold",
    steps: [
      "Start a new game in New Bark Town",
      "Visit Professor Elm and choose your starter Pokemon",
      "Travel toward Mr. Pokemon's house",
      "Receive the Mystery Egg and Professor Oak encounter",
      "Return toward New Bark Town",
      "Battle the rival after the theft event",
      "Return the Mystery Egg to Professor Elm",
      "Receive Poke Balls and begin catching Pokemon",
      "Travel to Violet City",
      "Explore Sprout Tower if desired / required progression setup",
      "Defeat Falkner and earn the Zephyr Badge",
      "Head south and then west toward Azalea Town",
      "Enter Slowpoke Well",
      "Defeat Team Rocket in Slowpoke Well",
      "Defeat Bugsy and earn the Hive Badge",
      "Travel through Ilex Forest",
      "Reach Goldenrod City",
      "Defeat Whitney and earn the Plain Badge",
      "Handle the Goldenrod Radio / side events as needed",
      "Travel north and then west toward Ecruteak City",
      "Visit the Burned Tower story event",
      "Defeat Morty and earn the Fog Badge",
      "Travel west to Olivine City",
      "Visit the Lighthouse and help Jasmine",
      "Surf to Cianwood City",
      "Defeat Chuck and earn the Storm Badge",
      "Receive HM02 Fly and return to Olivine",
      "Defeat Jasmine and earn the Mineral Badge",
      "Travel to Mahogany Town",
      "Clear the Lake of Rage / Red Gyarados event",
      "Infiltrate and clear Team Rocket Hideout",
      "Defeat Pryce and earn the Glacier Badge",
      "Return to Goldenrod City for the Team Rocket takeover",
      "Clear Team Rocket from Goldenrod Radio Tower",
      "Travel east to Blackthorn City",
      "Defeat Clair and earn the Rising Badge after the Dragon's Den trial",
      "Receive access to the Pokemon League",
      "Travel through Victory Road",
      "Reach Indigo Plateau",
      "Challenge Will of the Elite Four",
      "Challenge Koga of the Elite Four",
      "Challenge Bruno of the Elite Four",
      "Challenge Karen of the Elite Four",
      "Defeat Champion Lance",
      "Complete the Johto main story",
      "Receive the S.S. Ticket and travel to Kanto",
      "Visit Vermilion City and begin the Kanto badge quest",
      "Defeat Lt. Surge and earn the Thunder Badge",
      "Restore the Power Plant / Magnet Train side story",
      "Defeat Misty and earn the Cascade Badge",
      "Defeat Sabrina and earn the Marsh Badge",
      "Defeat Erika and earn the Rainbow Badge",
      "Defeat Janine and earn the Soul Badge",
      "Defeat Brock and earn the Boulder Badge",
      "Defeat Blaine and earn the Volcano Badge",
      "Unlock Viridian Gym by finishing the related Kanto events",
      "Defeat Blue and earn the Earth Badge",
      "Receive access to Mt. Silver",
      "Train your team and explore Mt. Silver",
      "Defeat Red on Mt. Silver and finish the major postgame goal",
    ],
  },
];
