const kantoAreas = [
  // {
  //   id: "indigo-plateau",
  //   name: "Indigo Plateau",
  //   type: "League",
  //   polygon: [
  //     [0, 0],
  //     [53, 0],
  //     [53, 90],
  //     [0, 90],
  //   ],
  //   pokemon: [],
  //   note: "Pokémon League and Elite Four.",
  // },
  // {
  //   id: "victory-road",
  //   name: "Victory Road",
  //   type: "Cave",
  //   polygon: [
  //     [0, 91],
  //     [53, 91],
  //     [53, 293],
  //     [0, 293],
  //   ],
  //   pokemon: ["Machoke", "Onix", "Golbat", "Geodude"],
  //   note: "Final cave route before Indigo Plateau.",
  // },
  {
    id: "route-23",
    name: "Route 23",
    type: "Route",
    polygon: [
      [0, 140],
      [105, 140],
      [105, 813],
      [0, 813],
    ],
    pokemon: ["Fearow", "Arbok", "Primeape"],
    note: "Badge gate road from Viridian west toward the League approach.",
  },
  {
    id: "route-22",
    name: "Route 22",
    type: "Route",
    polygon: [
      [0, 842],
      [212, 842],
      [212, 943],
      [0, 943],
    ],
    pokemon: ["Nidoran-M", "Nidoran-F", "Mankey", "Spearow"],
    note: "Western route from Viridian City.",
  },
  {
    id: "pewter-city",
    name: "Pewter City",
    type: "City",
    polygon: [
      [213, 266],
      [422, 266],
      [422, 440],
      [213, 440],
    ],
    pokemon: [],
    note: "Home of Brock and the Pewter Museum.",
    connections: { South: "Route 2", East: "Route 3" },
  },
  {
    id: "route-2",
    name: "Route 2",
    type: "Route",
    polygon: [
      [264, 440],
      [370, 440],
      [370, 797],
      [264, 797],
    ],
    pokemon: ["Pidgey", "Rattata", "Caterpie", "Weedle"],
    note: "Long north-south route linking Viridian City, Viridian Forest and Pewter City.",
  },

  {
    id: "route-3",
    name: "Route 3",
    type: "Route",
    polygon: [
      [422, 305],
      [790, 305],
      [790, 395],
      [422, 395],
    ],
    pokemon: ["Spearow", "Jigglypuff", "Nidoran♀", "Nidoran♂"],
    note: "The eastern road from Pewter to Mt. Moon.",
  },
  {
    id: "route-4",
    name: "Route 4",
    type: "Route",
    polygon: [
      [690, 224],
      [1166, 224],
      [1166, 306],
      [690, 306],
    ],
    pokemon: ["Rattata", "Spearow", "Ekans", "Sandshrew"],
    note: "Route east of Mt. Moon leading into Cerulean City.",
  },
  {
    id: "cerulean-city",
    name: "Cerulean City",
    type: "City",
    polygon: [
      [1168, 180],
      [1375, 180],
      [1375, 340],
      [1168, 340],
    ],
    pokemon: [],
    note: "Misty’s city and the northern bridge hub.",
    connections: { West: "Route 4", North: "Route 24", East: "Route 9", South: "Route 5" },
  },
  {
    id: "route-24",
    name: "Route 24",
    type: "Route",
    polygon: [
      [1220, 0],
      [1322, 0],
      [1322, 176],
      [1220, 176],
    ],
    pokemon: ["Abra", "Bellsprout", "Oddish", "Caterpie", "Weedle"],
    note: "Nugget Bridge route north of Cerulean.",
  },
  {
    id: "route-25",
    name: "Route 25",
    type: "Route",
    polygon: [
      [1322, 0],
      [1640, 0],
      [1640, 88],
      [1322, 88],
    ],
    pokemon: ["Abra", "Bellsprout", "Oddish", "Caterpie", "Weedle"],
    note: "The long eastern cape route to Bill’s cottage.",
  },
  {
    id: "route-9",
    name: "Route 9",
    type: "Route",
    polygon: [
      [1376, 222],
      [1700, 222],
      [1700, 307],
      [1376, 307],
    ],
    pokemon: ["Rattata", "Spearow", "Ekans", "Sandshrew"],
    note: "East from Cerulean toward Rock Tunnel.",
  },
  {
    id: "route-10",
    name: "Route 10",
    type: "Route",
    polygon: [
      [1697, 223],
      [1800, 223],
      [1800, 575],
      [1697, 575],
    ],
    pokemon: [
      "Voltorb",
      "Spearow",
      "Ekans",
      "Tentacool",
      "Magikarp",
      "Horsea",
      "Krabby",
      "Gyarados",
      "Psyduck",
    ],
    note: "",
  },
  {
    id: "lavender-town",
    name: "Lavender Town",
    type: "Town",
    polygon: [
      [1697, 575],
      [1800, 575],
      [1800, 659],
      [1697, 659],
    ],
    pokemon: [],
    note: "Quiet town with Pokémon Tower.",
    connections: { West: "Route 10", South: "Route 12", "SW": "Route 8" },
  },
  {
    id: "route-5",
    name: "Route 5",
    type: "Route",
    polygon: [
      [1165, 336],
      [1375, 336],
      [1375, 537],
      [1165, 537],
    ],
    pokemon: ["Pidgey", "Oddish", "Meowth"],
    note: "The vertical route south from Cerulean.",
  },
  {
    id: "route-7",
    name: "Route 7",
    type: "Route",
    polygon: [
      [1057, 575],
      [1165, 575],
      [1165, 662],
      [1057, 662],
    ],
    pokemon: ["Growlithe", "Vulpix", "Meowth"],
    note: "Westward route from Saffron toward Celadon.",
  },
  {
    id: "route-8",
    name: "Route 8",
    type: "Route",
    polygon: [
      [1375, 574],
      [1677, 574],
      [1677, 662],
      [1375, 662],
    ],
    pokemon: ["Growlithe", "Vulpix", "Meowth", "Kadabra"],
    note: "Eastern edge of Celadon leading into Saffron.",
  },
  {
    id: "route-6",
    name: "Route 6",
    type: "Route",
    polygon: [
      [1218, 707],
      [1323, 707],
      [1323, 874],
      [1218, 874],
    ],
    pokemon: ["Pidgey", "Oddish", "Meowth"],
    note: "South from Saffron to Vermilion.",
  },
  {
    id: "route-11",
    name: "Route 11",
    type: "Route",
    polygon: [
      [1375, 927],
      [1694, 927],
      [1694, 1015],
      [1375, 1015],
    ],
    pokemon: ["Drowzee", "Spearow", "Ekans", "Sandshrew"],
    note: "East from Vermilion and access to Diglett’s Cave area.",
  },
  {
    id: "route-12",
    name: "Route 12",
    type: "Route",
    polygon: [
      [1697, 660],
      [1800, 660],
      [1800, 1192],
      [1697, 1192],
    ],
    pokemon: ["Tentacool", "Magikarp", "Oddish", "Bellsprout"],
    note: "Long coastal route south from Lavender.",
  },
  {
    id: "saffron-city",
    name: "Saffron City",
    type: "City",
    polygon: [
      [1166, 535],
      [1375, 535],
      [1375, 704],
      [1166, 704],
    ],
    pokemon: [],
    note: "Central metropolis with Silph Co. and Sabrina’s Gym.",
    connections: { North: "Route 5", South: "Route 6", West: "Route 7", East: "Route 8" },
  },
  {
    id: "vermilion-city",
    name: "Vermilion City",
    type: "City",
    polygon: [
      [1166, 885],
      [1375, 885],
      [1375, 1060],
      [1166, 1060],
    ],
    pokemon: [],
    note: "Harbor city with the S.S. Anne and Lt. Surge’s Gym.",
    connections: { North: "Route 6", East: "Route 11" },
  },
  {
    id: "celadon-city",
    name: "Celadon City",
    type: "City",
    polygon: [
      [795, 532],
      [1057, 532],
      [1057, 704],
      [795, 704],
    ],
    pokemon: [],
    note: "Department Store, Game Corner, and Erika’s Gym.",
    connections: { East: "Route 7", West: "Route 16", South: "Route 17" },
  },
  {
    id: "route-16",
    name: "Route 16",
    type: "Route",
    polygon: [
      [582, 575],
      [793, 575],
      [793, 662],
      [582, 662],
    ],
    pokemon: ["Spearow", "Doduo"],
    note: "Western gate route out of Celadon.",
  },
  {
    id: "route-17",
    name: "Route 17",
    type: "Route",
    polygon: [
      [582, 662],
      [687, 662],
      [687, 1369],
      [582, 1369],
    ],
    pokemon: ["Doduo", "Fearow", "Ponyta", "Raticate"],
    note: "The long vertical bike-only road from Celadon to Fuchsia.",
  },
  // {
  //   id: "viridian-forest",
  //   name: "Viridian Forest",
  //   type: "Forest",
  //   polygon: [
  //     [0, 264],
  //     [124, 264],
  //     [124, 559],
  //     [0, 559],
  //   ],
  //   pokemon: ["Caterpie", "Metapod", "Weedle", "Kakuna", "Pikachu"],
  //   note: "Large early forest west of Route 2.",
  // },
  // {
  //   id: "route-2-north",
  //   name: "Route 2",
  //   type: "Route",
  //   polygon: [
  //     [264, 440],
  //     [367, 440],
  //     [367, 797],
  //     [264, 797],
  //   ],
  //   pokemon: ["Pidgey", "Rattata", "Caterpie", "Weedle"],
  //   note: "Route south of Pewter leading into Viridian Forest.",
  // },
  {
    id: "viridian-city",
    name: "Viridian City",
    type: "City",
    polygon: [
      [213, 797],
      [422, 797],
      [422, 968],
      [213, 968],
    ],
    pokemon: [],
    note: "The city just north of Pallet and west of Route 22.",
    connections: { North: "Route 2", South: "Route 1", East: "Route 22", West: "Route 23" },
  },
  {
    id: "route-1",
    name: "Route 1",
    type: "Route",
    polygon: [
      [265, 971],
      [368, 971],
      [368, 1146],
      [265, 1146],
    ],
    pokemon: ["Pidgey", "Rattata"],
    note: "Simple route between Pallet Town and Viridian City.",
  },
  {
    id: "pallet-town",
    name: "Pallet Town",
    type: "Town",
    polygon: [
      [265, 1146],
      [368, 1146],
      [368, 1234],
      [265, 1234],
    ],
    pokemon: [],
    note: "Your hometown and starting point.",
    connections: { North: "Route 1", South: "Route 21" },
  },
  {
    id: "route-21",
    name: "Route 21",
    type: "Sea",
    polygon: [
      [264, 1236],
      [368, 1236],
      [368, 1678],
      [264, 1678],
    ],
    pokemon: ["Tentacool", "Tentacruel"],
    note: "Sea route from Pallet down to Cinnabar.",
  },
  {
    id: "cinnabar-island",
    name: "Cinnabar Island",
    type: "Island",
    polygon: [
      [264, 1678],
      [368, 1678],
      [368, 1766],
      [264, 1766],
    ],
    pokemon: [],
    note: "Island town with Blaine’s Gym.",
    connections: { North: "Route 21", East: "Route 20" },
  },
  {
    id: "route-20",
    name: "Route 20",
    type: "Sea",
    polygon: [
      [368, 1678],
      [900, 1678],
      [900, 1766],
      [368, 1766],
    ],
    pokemon: ["Tentacool", "Tentacruel"],
    note: "Sea route between Cinnabar and Seafoam.",
  },
  {
    id: "route-19",
    name: "Route 19",
    type: "Sea",
    polygon: [
      [900, 1500],
      [1005, 1500],
      [1005, 1766],
      [900, 1766],
    ],
    pokemon: ["Tentacool", "Tentacruel"],
    note: "Sea route south of Fuchsia.",
  },
  // {
  //   id: "seafoam-islands",
  //   name: "Seafoam Islands",
  //   type: "Cave",
  //   polygon: [
  //     [349, 1364],
  //     [504, 1364],
  //     [504, 1460],
  //     [349, 1460],
  //   ],
  //   pokemon: ["Seel", "Zubat", "Krabby", "Articuno"],
  //   note: "Island cave complex in the southern sea.",
  // },
  {
    id: "route-18",
    name: "Route 18",
    type: "Route",
    polygon: [
      [583, 1368],
      [874, 1368],
      [874, 1455],
      [583, 1455],
    ],
    pokemon: ["Doduo", "Raticate"],
    note: "Bottom of Cycling Road near Fuchsia.",
  },
  // {
  //   id: "safari-zone",
  //   name: "Safari Zone",
  //   type: "Safari Zone",
  //   polygon: [
  //     [479, 1067],
  //     [679, 1067],
  //     [679, 1212],
  //     [479, 1212],
  //   ],
  //   pokemon: ["Tauros", "Kangaskhan", "Scyther", "Pinsir", "Chansey"],
  //   note: "Special capture area northwest of Fuchsia.",
  // },
  {
    id: "fuchsia-city",
    name: "Fuchsia City",
    type: "City",
    polygon: [
      [848, 1326],
      [1057, 1326],
      [1057, 1500],
      [848, 1500],
    ],
    pokemon: [],
    note: "Koga’s city and the entrance to Safari Zone.",
    connections: { North: "Route 15", East: "Route 14", South: "Route 19", West: "Route 18" },
  },
  {
    id: "route-14",
    name: "Route 14",
    type: "Route",
    polygon: [
      [1377, 1194],
      [1483, 1194],
      [1483, 1455],
      [1377, 1455],
    ],
    pokemon: ["Pidgeotto", "Fearow", "Doduo"],
    note: "Upper eastward route from Fuchsia.",
  },
  {
    id: "route-15",
    name: "Route 15",
    type: "Route",
    polygon: [
      [1057, 1368],
      [1376, 1368],
      [1376, 1456],
      [1057, 1456],
    ],
    pokemon: ["Oddish", "Venonat", "Bellsprout"],
    note: "Lower eastward route from Fuchsia.",
  },
  {
    id: "route-13",
    name: "Route 13",
    type: "Route",
    polygon: [
      [1483, 1194],
      [1800, 1194],
      [1800, 1280],
      [1483, 1280],
    ],
    pokemon: ["Ditto", "Venonat", "Wingull"],
    note: "Coastal route connecting east coast lines to Route 12.",
  },
];

export const mapData = {
  "fire-red": {
    regionName: "Kanto",
    image: "/maps/kanto.png",
    imageHD: "/maps/kanto-hd.png",
    width: 1800,
    height: 1766,
    areas: kantoAreas,
  },
};
